### ISSUE TITLE
Feature request: Config file support for url/tokens to multiple environments

### ISSUE THREAD

**Issue by nervetattoo** [grafana/grizzly#113]
Just started testing Grizzly, and so long this is the key piece I feel could be built in.
I would love to be able to do something like `grr apply --env prod dashboards.jsonnet` and have it read a `.grizzly.jsonnet` containing something like
```jsonnet
{
  environments: {
    test: { url: 'https://test.grafana.domain.com', token: 'foo' },
    prod: { url: 'https://prod.grafana.domain.com', token: 'bar' }
  }
}
```

I could wrap it in my own apply-script, but I assume this type of need is common. Added bonus would be passing `--env prod,test` to apply to both.

**Comment by julienduchesne** [comment]
Superseded by https://github.com/grafana/grizzly/issues/315. Support for contexts was added in v0.3.0
