### ISSUE TITLE
"grr preview" should only generate snapshots where there are differences

### ISSUE THREAD

**Issue by rhowe** [grafana/grizzly#138]
My use case: I am deploying dashboards from a CI pipeline, where PRs run `grr preview` to generate dashboard snapshots reviewers can use to view what the resulting dashboard looks like as part of the review process.

Since this pipeline publishes many dashboards, `grr preview` generates many snapshots, even if some of the dashboards are unchanged. It would make for a more pleasant review experience if snapshots were only generated for dashboards which contained modifications (or were new). Maybe this should be optional, via a commandline argument.

**Comment by malcolmholmes** [comment]
We're not planning on improving the preview feature. It relies on snapshots, which are generally considered a "legacy" feature. And we won't be able to create a similar workflow for other resources (e.g. alert rules). We're currently exploring `grr serve` for dashboards as a solution that could conceivably be expanded to other resource types.

I'm closing this issue now, but feel free to make a PR if you think this is useful to you.
