### ISSUE TITLE
Suggestion: make "watch" an option

### ISSUE THREAD

**Issue by shettich** [grafana/grizzly#164]
Consider making watch into an option that can be applied to either apply or preview

A great developer workflow would be to have preview in watch mode, so each time I save my changes are validated/pushed and if I have a browser open it updates (would need to keep re-pushing to the same place)

**Comment by beasteers** [comment]
It would also be great as an option for pull, so that changes made via the UI could be synched for to source control

**Comment by K-Phoen** [comment]
Closing this, since the `grr serve` command sounds like it would fit your use-case
