### ISSUE TITLE
"apply" does not create folders before dashboards

### ISSUE THREAD

**Issue by shettich** [grafana/grizzly#165]
When I try apply with a new dash and a new folder, it first tries to create the dashboard, and that fails when it can't find the folder.

It should create the folders first.

**Comment by shettich** [comment]
FWIW, I did a quick check, and adding support for sort.Sort() (Len/Swap/Less) to the Resources type (sorting by Kind()), and then sorting at the start of Apply() makes it work

**Comment by malcolmholmes** [comment]
This PR https://github.com/grafana/grizzly/pull/162 should have resolved this issue.

**Comment by rhowe** [comment]
Also a dupe of https://github.com/grafana/grizzly/issues/143
