### ISSUE TITLE
Improve Diff Output For New Dashboards

### ISSUE THREAD

**Issue by keithherron** [grafana/grizzly#167]
Currently when running `grr diff` with a new dashboard that hasn't been applied to Grafana yet, I'm seeing:

`Dashboard/dashboard_name not present in Dashboard`

I wasn't entirely sure at first what this meant or if it was good or bad, but AIUI it means the dashboard doesn't exist yet in Grafana, so no diff is being shown.

I think this could be easier to understand if the diff for a new dashboard output something to the effect of: 

`Dashboard/dashboard_name changes detected (create dashboard)`

Ideally with the option to print a full diff containing the new dashboard json that would be applied.

**Comment by malcolmholmes** [comment]
The main issue I have with the message you mention above is that "Dashboard" isn't a place where a dashboard exists - **Grafana** is the place where a dashboard exists. I need to add the concept of "system" so the message becomes:
```
Dashboard/dashboard_uid not present in Grafana
```
Would that do it?

**Comment by malcolmholmes** [comment]
Actually, please try the latest release of Grafana. This has changed a *lot*. I'd like to think it is much cleaner now.

**Comment by malcolmholmes** [comment]
Closing. Please reopen if still an issue.
