### ISSUE TITLE
Field "Name" missing when applying datasource

### ISSUE THREAD

**Issue by tenstad** [grafana/grizzly#181]
## Error
`Non-200 response from Grafana while applying datasource prometheus: 422 Unprocessable Entity [{"fieldNames":["Name"],"classification":"RequiredError","message":"Required"}]`

## How to reproduce
In the [`examples/`](https://github.com/grafana/grizzly/tree/master/examples) folder, run `grr apply grr.jsonnet`.

## Suggested solution
Add `spec["name"] = m.Metadata().Name()` below [`spec["uid"] = m.Metadata().Name()`](https://github.com/grafana/grizzly/blob/master/pkg/grafana/datasource-handler.go#L88).

**Comment by malcolmholmes** [comment]
This I believe works now.
