### ISSUE TITLE
Library Panels / Grafana 8.x support?

### ISSUE THREAD

**Issue by briend** [grafana/grizzly#191]
Grizzly appears to work well with Grafana 8.x, however if a dashboard uses Library Panels, those panels are not exported (or imported) via `grr pull` and `grr apply`, respectively.

https://grafana.com/docs/grafana/latest/http_api/library_element/

**Comment by ccjones88** [comment]
Just tried using Grizzly and ran into the same issue as you @briend. Did you happen to find a solution/workaround in the meantime?

**Comment by malcolmholmes** [comment]
See #218. Needs review before merging.

**Comment by fahmizulhasymi** [comment]
Looking forward to see this feature available on stable releases.

Since the https://github.com/grafana/grizzly/pull/218 already being reviewed, is there any timeline to release it?

**Comment by HabibMAALEM** [comment]
@malcolmholmes we can apply the use of the official Grafana client for all requests #250 not only for Library Panels

**Comment by malcolmholmes** [comment]
Doing so would reduce the size of the codebase, so is a good idea. Just haven't done the work.

**Comment by julienduchesne** [comment]
Support for library panels was added in v0.3.0
