### ISSUE TITLE
Make upgrade 1.0 -> 2.0 documentation

### ISSUE THREAD

**Issue by m-messiah** [grafana/grizzly#219]
Hello! There is long time passed after code migration to 2.0, so it looks like there is a good time to get an instruction of how to migrate the existing jsonnet definitions from grr version 1.0 to 2.0. 
For example, I use grafonnet-lib and the simple dashboard looks almost like:

```jsonnet
{
  grafanaDashboardFolder: 'test',
  grafanaDashboards+:: {
    [std.thisFile]: grafana.dashboard.new(
        title='test',
        uid='test',
        schemaVersion=16,
        time_from='now-6h',
        refresh='1m',
        graphTooltip='shared_crosshair',
      ).addPanels(
        [
          grafana.row.new(title='test')
        ] + [
          grafana.graphPanel.new(title='test', datasource='randomWalk').addTargets(grafana.prometheus.target(expr='up'))
        ]
      ),
  },
}
```

So what is the best way to convert tons of similar dashboards to Kubernetes objects for grr 2.0?

**Comment by malcolmholmes** [comment]
There's a library in github.com/grafana/jsonnet-libs/grizzly that can do this: https://github.com/grafana/jsonnet-libs/blob/master/grizzly/grizzly.libsonnet#L7-L17
