### ISSUE TITLE
grr preview fails with recent Grafana

### ISSUE THREAD

**Issue by rhowe** [grafana/grizzly#227]
Recent grafana releases (at least 9.1.8) appear to have broken grizzly's preview feature.

Running `grr preview` now results in an error such as

    time=<timestamp> level=fatal msg="Non-200 response from Grafana while applying snapshot mydashboard-uid: 400 Bad Request \"Creating a local snapshot requires a dashboard\"\n"

**Comment by HabibMAALEM** [comment]
I created an issue to fix this problem globally #250

**Comment by malcolmholmes** [comment]
I'm going to assume this is resolved by the new openapi client. Please re-open if not yet resolved.
