### ISSUE TITLE
Provide homebrew installation

### ISSUE THREAD

**Issue by remyleone** [grafana/grizzly#228]
As a macOS user, I would like to have my packages managed by a single tool. Could you provide a homebrew method of installation for grizzly on the documentation: https://grafana.github.io/grizzly/installation/

**Comment by bcdady** [comment]
It would also be nice to see someone make grr available via the [asdf-vm tool](https://github.com/asdf-community).

**Comment by malcolmholmes** [comment]
I'm sure I would accept PRs offering such support.

**Comment by chewrocca** [comment]
Submitted https://github.com/Homebrew/homebrew-core/pull/183138

**Comment by chewrocca** [comment]
https://github.com/Homebrew/homebrew-core/pull/183138 added Grizzly

**Comment by remyleone** [comment]
Thanks a lot :) I hope completion at install time will be added after. ☺️

Le lun. 2 sept. 2024, 16:49, Matthew Fine ***@***.***> a
écrit :
