### ISSUE TITLE
`grr list -r` fatal error on RuleGroup

### ISSUE THREAD

**Issue by samlaf** [grafana/grizzly#242]
running `grr list -r` returns
```
INFO[0000] Listing remotes
FATA[0000] yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `success` into []rwrulefmt.RuleGroup
  line 1: cannot unmarshal !!map into []rwrulefmt.RuleGroup
  line 1: cannot unmarshal !!str `` into []rwrulefmt.RuleGroup
  line 1: cannot unmarshal !!str `` into []rwrulefmt.RuleGroup
```
also getting errors when trying to pull all resources.
Any idea where this error might be coming from, and how I could change my ruleGroups (these are from alerts right?) to get grizzly to stop complaining?

**Comment by malcolmholmes** [comment]
Closing as Grizzly has changed a lot since, and this appears to work for me. If still an issue, feel free to re-open.
