### ISSUE TITLE
grr export writes YAML files with .json extension

### ISSUE THREAD

**Issue by robbat2** [grafana/grizzly#248]
`grr export src/grr.jsonnet dst/` generates files into the `dst/` directory as expected, but they are YAML content written into files with a JSON extension.

**Comment by samarara** [comment]
Seeing this too.

**Comment by samarara** [comment]
@robbat2 I tried converting them via a combination of `yq` and `jq` like so: 
```
yq -o=json ~/path/to/exported/yaml/chunks.json | jq ".spec"
```
and that did the trick for me.

**Comment by robbat2** [comment]
I can convert them file, I just want it to use the correct file extension when saving.

**Comment by malcolmholmes** [comment]
This is resolved. Grizzly can now output in both YAML *and* JSON with the -o parameter.
