### ISSUE TITLE
Document installation of Grizzly

### ISSUE THREAD

**Issue by tanveermunavar** [grafana/grizzly#25]
Hi Team,

How to install this tool ?

**Comment by malcolmholmes** [comment]
Hi, this tool is extremely new, and doesn't yet have installation tooling. You will need to build it yourself, which should just involve installing a modern Golang, then, if you have `make` do `make dev` and it should create a `grr` binary that you can place wherever you need it (e.g. `/usr/local/bin`). Or, without make, do `go build ./cmd/grr`.

I've renamed this issue to take account of the fact that we need to document this properly.

**Comment by malcolmholmes** [comment]
We now have an initial release, see here: https://github.com/grafana/grizzly/releases/tag/v0.0.1. It has some basic install instructions, at least for Linux/MacOS.

**Comment by malcolmholmes** [comment]
Installation of binaries should be straightforward enough for people willing to use a tool such as this.
