### ISSUE TITLE
Use Grafana official golang client

### ISSUE THREAD

**Issue by HabibMAALEM** [grafana/grizzly#250]
Replace the HttpClient by the Grafana Golang client https://github.com/grafana/grafana-api-golang-client to reduce base code which implies less maintenance and keep Grizzly compatible with Grafana API
In addition, it brings more flexibility in the settings :

- Target a specific organization
- Retriable requests
- The choice to use Basic and Bearer authentication

**Comment by malcolmholmes** [comment]
We now use the new openapi generated client (https://github.com/grafana/grafana-openapi-client-go).
