### ISSUE TITLE
Image with tag latest is not latest

### ISSUE THREAD

**Issue by tenstad** [grafana/grizzly#253]
The `latest` tag is not the latest release (`0.2.1`). It's somewhere inbetween `0.2.0` and `0.2.1`.
- `latest` https://github.com/grafana/grizzly/commit/51a1d08 https://github.com/grafana/grizzly/pull/225
- `0.2`/`0.2.1` https://github.com/grafana/grizzly/commit/1510b15 https://github.com/grafana/grizzly/pull/238
- `0.2.0` https://github.com/grafana/grizzly/commit/e77f5c7 https://github.com/grafana/grizzly/pull/212
- `0.1`/`0.1.0` https://github.com/grafana/grizzly/commit/b719359 https://github.com/grafana/grizzly/pull/81

Source:
```sh
docker run --rm -it docker.io/grafana/grizzly:latest --version
2023-08-18 09:43:03.524351 I | grr version 51a1d08

docker run --rm -it docker.io/grafana/grizzly:0.2 --version
2023/08/18 09:43:07 grr version 1510b15

docker run --rm -it docker.io/grafana/grizzly:0.2.1 --version
2023/08/18 09:47:22 grr version 1510b15

docker run --rm -it docker.io/grafana/grizzly:0.2.0 --version
2023-08-18 09:47:35.935853 I | grr version e77f5c7

docker run --rm -it docker.io/grafana/grizzly:0.1 --version
grr version b719359

docker run --rm -it docker.io/grafana/grizzly:0.1.0 --version
grr version b719359
```

**Comment by julienduchesne** [comment]
The release workflows have been re-done and this is now fixed. `latest` tracks the main branch
