### ISSUE TITLE
Disable SSL verification

### ISSUE THREAD

**Issue by NicoAdrian** [grafana/grizzly#256]
Hello,

Is there any way to disable SSL verification when using `grr` CLI ? 

I get this error: `x509: certificate signed by unknown authority`

**Comment by joanlopez** [comment]
Hello @NicoAdrian,

I don't think there's any way to disable SSL verification for now. 

I'm even wondering if that's something we would like to add support for, cause generally _"Disabling security checks is dangerous and should be avoided"_. But, let me discuss it with the team, I'll be back with an answer.

Thanks!

**Comment by ShadowUser17** [comment]
When do you plan to add support to this feature?

**Comment by malcolmholmes** [comment]
I've just merged #363 which uses the golang "insecure-skip-verify" feature. This will allow you to get past an invalid expiry, but won't work in all scenarios (e.g. an incorrectly configured hostname). Not much more we can do as I understand it.
