### ISSUE TITLE
Authenticate with session cookie

### ISSUE THREAD

**Issue by l2dy** [grafana/grizzly#258]
With limited permissions scoped under a certain folder, I could not create an API token in our Grafana instance, but I do have session cookies acquired using regular login. Would it be possible to authenticate with session cookie?

**Comment by malcolmholmes** [comment]
I'm currently not aware of a way to make this happen. I'd love to see a way to do something like Google's `gcloud` command does: `gcloud auth login` calls out to a browser window, you authenticate, grant permissions, then it 'hands back' to the CLI command, which is now authenticated. But, that will likely require modifications to Grafana, and as yet I don't know how to do that.

I'm going to keep this issue open, as I think it would be a useful addition for some point in the future.

**Comment by K-Phoen** [comment]
Duplicates #451, which is closed (see https://github.com/grafana/grizzly/issues/451#issuecomment-2419570493)
