### ISSUE TITLE
"grr get DashboardFolder." leads to unmarshall error

### ISSUE THREAD

**Issue by robbat2** [grafana/grizzly#263]
Trying to export a list of folders from the server, and it cannot unmarshall. Output below was redacted.

```
$ grr get DashboardFolder.
INFO[0000] Getting DashboardFolder.                     
FATA[0000] Error retrieving dashboard folder : Failed to parse Grafana response: json: cannot unmarshal array into Go value of type grafana.Folder.

Response:
[{"id":n,"uid":"x","title":"x"},...,{"id":n,"uid":"x","title":"x"}]
```

**Comment by malcolmholmes** [comment]
The syntax of your command is invalid, as it should be `${kind}.${uid}` and your UID is blank.

However, it should give a nicer error than the one you received. Making a PR.

**Comment by robbat2** [comment]
What's the expected way to ask `grr` to list the objects of KIND then? I do want the JSON list output.

**Comment by malcolmholmes** [comment]
`grr list -r -t Dashboards` should for example list the remote dashboards.

**Comment by robbat2** [comment]
Sorry, that doesn't list remote Dashboards at all. Output (heavily redacted): it gives zero output. This is an internal deployment of Grafana, not Grafana Cloud.

```
$ grr --version
2024-03-31 22:12:37.605949 I | grr version v0.2.0

$ export GRAFANA_TOKEN=glsa_(redacted) GRAFANA_URL=http://grafana(redacted)/ 

$ grr list -t -r Dashboards
FATA[0000] Dashboards must be yaml, json or jsonnet     

$ grr list  -r -t  Dashboards
INFO[0000] Listing remotes                              
API VERSION    KIND    UID

$ grr get DashboardFolder. 
INFO[0000] Getting DashboardFolder.                     
FATA[0000] Error retrieving dashboard folder : Failed to parse Grafana response: json: cannot unmarshal array into Go value of type grafana.Folder.

Response:
[{"id":nnn,"uid":"(redacted)","title":"(redacted)"},{"id":nnn,"uid":"(redacted)","title":"(redacted)"}, ... ]
```

**Comment by malcolmholmes** [comment]
(I see the error above, should be `Dashboard` not `Dashboards`)

I just added list formatting today. You can now do:

```
grr list -r -t Dashboard -f json
```
and it will return a list of remote dashboard resources, as a JSON list.

This is in the v0.4.1 release made today.

**Comment by robbat2** [comment]
Thanks; I confirm it works!
