### ISSUE TITLE
Kubernetes Operator

### ISSUE THREAD

**Issue by sathieu** [grafana/grizzly#272]
Could grizzly be run as a Kubernetes Operator with custom resources definitions for Orgs, Datasources, Dashboard, ... ?

**Comment by malcolmholmes** [comment]
This is not something that it has been designed for at this point. Can you not use the existing [Grafana Operator](https://github.com/grafana-operator/grafana-operator)?

**Comment by malcolmholmes** [comment]
In terms of automation, Grizzly is more likely to run in a CI job and push resources from there.

**Comment by sathieu** [comment]
@malcolmholmes OK. This is hard to find a complete solution for my usecase, all of the evaluated solutions have missing features :

- Grafana provisioning is not able to use OrgName for datasources and dashboard (I created [grafana#76937](https://github.com/grafana/grafana/pull/76937) which is blocked by an [unscheduled UID migration](https://github.com/grafana/grafana/issues/77282#issuecomment-1810721909))
- Grafana provisioning is not able to create Orgs (I created https://github.com/grafana/grafana/pull/78253, which was closed, pointing to grizzly)
- Grizzly has no Org management (https://github.com/grafana/grizzly/issues/268)
- Grizzly has no support for OrgName is datasources and dashboard (I just created https://github.com/grafana/grizzly/issues/278)
- Grafana Operator has no Org support (see [here](https://github.com/grafana-operator/grafana-operator/blob/d1d71a9e4d1592b92232d5a61e766a683d5dce83/controllers/client/grafana_client.go#L150))
- ...

**Comment by malcolmholmes** [comment]
There is already a Kubernetes operator for Grafana, so doesn't make sense to make Grafana operate in this way. Would make more sense to add support to respective tools than convert an existing tool.

Also, note that orgs is a feature in Grafana that is unlikely to see much development - more likely to see it removed some time in the future.
