### ISSUE TITLE
OrgName for Datasources and Dashboards

### ISSUE THREAD

**Issue by sathieu** [grafana/grizzly#278]
OrgId are internal to grafana, I want to attach Datasources and Dashboards to Orgs using Organization names.

**Comment by malcolmholmes** [comment]
How would the API be used to apply a resource to a different org?

**Comment by sathieu** [comment]
@malcolmholmes The admin API is needed to map org name to org IDs I think.

https://grafana.com/docs/grafana/latest/developers/http_api/org/#admin-organizations-api

**Comment by malcolmholmes** [comment]
yeah, but how do I provide a name or orgID to the datasource or dashboard APIs? Is it just with the `orgId=n` request param? (I've never used orgs).

**Comment by sathieu** [comment]
`orgId` is an attribute of the datasource or dashboard.

You would do something [like this](https://grafana.com/docs/grafana/latest/developers/http_api/data_source/) :

```
POST /api/datasources HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk

{
  "orgId": 42,     # <============ here
  "name":"test_datasource",
  "type":"graphite",
  "url":"http://mydatasource.com",
  "access":"proxy",
  "basicAuth":false
}
```

**Comment by sathieu** [comment]
We need :

- the ability to create (or delete) orgs (https://github.com/grafana/grizzly/issues/268)
- the ability to use orgName instead of orgId (this issue)

**Comment by malcolmholmes** [comment]
Okay, so you want to be able to say that a dashboard needs to go into an org by name rather than by ID (this issue).

I can see that #268 should be pretty easy to implement. However, I'm more reticent to support name to ID conversions. This would require additional HTTP requests for each resource to get, then potentially cache, the mappings, which would introduce a lot more complexity.

**Comment by malcolmholmes** [comment]
I'm going to keep #268 open, but I think responsibility for mapping org name to org ID rests in whatever code is managing your dashboards. E.g. if you use jsonnet, you can write a simple name->orgID mapping that presents the ID to Grafana while using name everywhere a human will see it.

Closing this issue. Feel free to reopen if you think I've missed something.

**Comment by sathieu** [comment]
Hello,

We ended up writing our Kubernetes Operator to manage:

- GrafanaInstances (i.e. connection to API)
- GrafanaOrgs
- GrafaOrgDatasources
- GrafanaOrgDashboards

It' available at: https://gitlab.com/kubitus-project/grafana-org-operator/#grafana-org-operator. Feedback welcome!
