### ISSUE TITLE
Error when applying prometheus_rule_groups

### ISSUE THREAD

**Issue by NicoAdrian** [grafana/grizzly#300]
Hello,

When I'm trying to `grr apply` a `prometheus_rule_groups`, I get this error:

```
ERRO[0000] error during request to cortex api            error="Get \"/api/v1/rules\": unsupported protocol scheme \"\"" method=GET url=/api/v1/rules
FATA[0000] Get "/api/v1/rules": unsupported protocol scheme ""
```

Any idea ?

**Comment by malcolmholmes** [comment]
Have you configured your Mimir/Cortex server? Have you provided a `cortextool` binary to Grizzly? (It doesn't call APIs directly, it shells out to `cortextool` for that.

**Comment by NicoAdrian** [comment]
Hello @malcolmholmes 

Cortex server is configured and just installed cortextool. How to "provide" it to grizzly ?

**Comment by malcolmholmes** [comment]
Either provide a `CORTEXTOOL_PATH` envvar, or it will look it up on your path. Then use the new "context" functionality to provide credentials (see grafana.github.io/grizzly/authentication/ for details).

**Comment by NicoAdrian** [comment]
thanks
