### ISSUE TITLE
Real hostname

### ISSUE THREAD

**Issue by gutorc92** [grafana/grizzly#35]
I deploy Grafana on a kubernetes cluster. I use an ingress to proxy my dns to my container then Grafana hostname stil localhost. On grizzly commands such as preview and apply the url returned is: ```http://localhost:3000/api/snapshots-delete/hzq2FJVuwih1oJTKSk8PsLJyWXqNY2m6 ```.  It will be useful to replace localhost with GRAFANA_HOST env value.

**Comment by malcolmholmes** [comment]
Closing as better options than `preview` (now renamed `snapshot`). Please reopen if still needed.
