### ISSUE TITLE
[Bug]: Docker image is broken

### ISSUE THREAD

**Issue by LacazeThomas** [grafana/grizzly#365]
### Grizzly Version

v0.4.0+

### Expected Behavior

```bash
$ grr config set grafana.user toto
```

### Actual Behavior

```bash
$ grr config set grafana.user toto
FATA[0000] open : no such file or directory
```

### Steps to Reproduce

```
$ docker run --rm -it --entrypoint sh grafana/grizzly:0.3.1
$ grr config set grafana.user toto
```

```
$ docker run --rm -it --entrypoint sh grafana/grizzly:0.4.0
$ grr config set grafana.user toto
FATA[0000] open : no such file or directory
$ grr config path
*empty*
```

same with 

```
$ docker run --rm -it --entrypoint bash golang:1.22
$ go install -a github.com/grafana/grizzly/cmd/grr@latest
$ grr config set grafana.user toto
FATA[0000] open : no such file or directory
$ grr config path
*empty*
```

**Comment by LacazeThomas** [comment]
fixed with `touch settings.yaml` in the current folder.

But this is still a regression compared to other versions.

**Comment by malcolmholmes** [comment]
You can still use Grizzly with environment variables, as before. I guess what you're saying is that, in your situation (inside Docker), it fails because it can't find a config file, even though you just want to use environment variables.

Have I got that right?
