### ISSUE TITLE
[Feature Request]:  Add jsonnet-lint to dockerfile

### ISSUE THREAD

**Issue by LacazeThomas** [grafana/grizzly#366]
### Feature Request

it would be great to add jsonnet-lint to the grizzly docker image.

https://github.com/google/go-jsonnet/tree/master/linter

```sh
go install github.com/google/go-jsonnet/cmd/jsonnet-lint@latest
```

**Comment by malcolmholmes** [comment]
How would this help Grizzly users?

**Comment by malcolmholmes** [comment]
I'm not sure that this is of great help to the majority of Grizzly users. I'd suggest creating your own Docker image on top of the Grizzly one.
