### ISSUE TITLE
[Feature Request]: Grizzly to skip over resources that have failed to export/import

### ISSUE THREAD

**Issue by wengelbrecht-grafana** [grafana/grizzly#376]
### Feature Request

It would be great if Grizzly can skip over failed resources during the export/import stages, instead of stopping/exiting. 
Or at least be more clear which resource is failing, so that it can be fixed. For example, this message isn't very clear: 

`FATA[0209] [POST /dashboards/db][400] postDashboardBadRequest {"message":"Cannot save provisioned dashboard"}`
If the above message could have the actual Dashboard name / Datasource Name / Alert Name, then that would be really helpful!

**Comment by malcolmholmes** [comment]
We now have `--continue-on-error` or `-e` which does this. Please reopen if this doesn't do it for you.
