### ISSUE TITLE
[Bug]: cannot config using grr config set

### ISSUE THREAD

**Issue by asdfedsf** [grafana/grizzly#377]
### Grizzly Version

0.4.0

### Expected Behavior

expect to config grafana URL etc as showing on documentation

grr config set grafana.url http://localhost:3000

### Actual Behavior

 cannot config using grr config set, got FATA error:

[root@st1lnpansible02 bin]# grr config set grafana.url http://10.5.32.38:3000
FATA[0000] open : no such file or directory   

Using strace showing it's trying to open a empty file:

$ strace -eopen,openat grr config set grafana.url
http://localhost:3000/
 
openat(AT_FDCWD, "/sys/kernel/mm/transparent_hugepage/hpage_pmd_size", O_RDONLY) = 3
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1832280, si_uid=818771538} ---
openat(AT_FDCWD, "/usr/local/bin/grr", O_RDONLY|O_CLOEXEC) = 3
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1832280, si_uid=818771538} ---
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1832280, si_uid=818771538} ---
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1832280, si_uid=818771538} ---
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1832280, si_uid=818771538} ---
openat(AT_FDCWD, "/etc/localtime", O_RDONLY) = 3
openat(AT_FDCWD, "", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0644) = -1 ENOENT (No such file or directory)
FATA[0000] open : no such file or directory             
+++ exited with 1 +++

### Steps to Reproduce

run the config set command:
grr config set grafana.url http://localhost:3000

**Comment by vmercierfr** [comment]
I have the same issue when building `grizzly` from `master` branch on MacBook M1 (ARM architecture).

I'm suspecting that since v4.0, Grizzly expect that the configuration file exists, but `grr config path` return empty result.

```bash
$ grr config path

```

A work around is to create the file manually before the configuration

```bash
touch /Users/$HOME/Library/Application\ Support/grizzly/settings.yaml
grr config set grafana.url http://localhost:3000
```

Or downgrade to Grizzly v0.3.1, set the configuration and upgrade to Grizzly v0.4.0.
