### ISSUE TITLE
[Regression]: Loss of preview functionality breaks Grafana Cloud dashboard workflows

### ISSUE THREAD

**Issue by tekicode** [grafana/grizzly#389]
### Grizzly Version

0.4.0

### Expected Behavior

Ability to preview changes to a dashboard with Continuous Integration without having to extend excessive permissions using API Keys or service accounts

### Actual Behavior

This PR removed the preview functionality: https://github.com/grafana/grizzly/pull/349 This functionality was the only way to 'preview' or snapshot changes to dashboards in a Grafana Cloud instances _without_ having a Service Account. That is: 'grr serve' does not work in a CI pipeline, and requires the use of a service account or API token by the human in order to make use of the functionality.

If `grr serve` could be made to work with OAuth Grafana Cloud logins, instead of depending upon API Keys, Service Accounts, or Basic Auth, that would restore this functionality: We would teach developers to use grr serve.

As it stands, it requires two accounts per human to make use of the tooling.

Previously, our CI pipeline would execute a preview on every changed dashboard, and give us about 10 hours to review it, plus the diff of the jsonnet file.

**Comment by malcolmholmes** [comment]
Thanks for your feedback. How does auth differ between the `preview` and the `serve` functionality? Is it just that a user/pass combination will work for preview but not serve?

Ideally a review should happen on a local workstation not requiring changes against an external Grafana instance.

**Comment by tekicode** [comment]
> Thanks for your feedback. How does auth differ between the `preview` and the `serve` functionality? Is it just that a user/pass combination will work for preview but not serve?
> 
> Ideally a review should happen on a local workstation not requiring changes against an external Grafana instance.

Thank you for the quick reply! Both the `serve` and `preview` functionality depend upon a service account to communicate to Grafana Cloud; however, the `preview` functionality allows us to restrict that account to a specific build pipeline. When the pipeline executes: it has the ability to create the previews which auto-expire. The developer can click on these previews and examine the results for any obvious issues in addition to the diff on the jsonnet.

We have not crafted a way for `serve` to result in, for example, spawned cloud-run jobs that remain connected to the cloud instance for a duration... that the engineer could browse to.

Ideally, we do not want developers/engineers, or on-call personnel to have a Service Account/API Key to communicate with Grafana Cloud. Presently, that is the only mechanism in which grizzly can be used with Grafana Cloud -- that or basic auth and we do not use basic auth.

For development on a local machine, we would need to permit direct access to the datasource from the engineers machine or to create fake data to simulate graphs. Neither is ideal.

Mostly just sort of taken aback at the removal of the preview/snapshot functionality. Seeing as this is a Grafana Cloud functionality, is that expected to disappear at some point?

Ultimately we could make use of `serve` if running serve would make an oauth2 call to login to an instance: I can provide my engineers with that instruction.

**Comment by malcolmholmes** [comment]
We've discussed this. Current thought: calling this feature "preview" is confusing because it has side-effects and preview doesn't imply that.

What if we reverted the removal and renamed the features snapshot?

**Comment by mikaello** [comment]
(ref comment in https://github.com/grafana/grizzly/pull/349#issuecomment-2009610260)

Reverting and renaming to *snapshot* would be nice!

We may find a way around with `serve`, but spawning jobs that keep running for the duration of the pull request lifetime (or just for a limited time) seems like a quite complex task, at least compared to how easy it was with the old `preview` functionality.

**Comment by malcolmholmes** [comment]
The idea with `serve` is that you do the review on your own laptop - just as you might with other code, so not within a CI job.

**Comment by tekicode** [comment]
> We've discussed this. Current thought: calling this feature "preview" is confusing because it has side-effects and preview doesn't imply that.
> 
> What if we reverted the removal and renamed the features snapshot?

Sounds good to me! We'd love to have this functionality restored, snapshot sounds like a good name
