### ISSUE TITLE
grafanaDashboardFolder field does not work

### ISSUE THREAD

**Issue by luizberti** [grafana/grizzly#43]
Currently on `v0.0.1`, this field seems to always get ignored. Simplest way to reproduce is adding it to the dashboard in `testdata`, and `grr apply` it:

```
{
  grafanaDashboardFolder: 'FOO',
  grafanaDashboards+:: {
    'my-dash.json': {
      uid: 'prod-overview',
      title: 'Production Overview',
      tags: ['templated'],
      timezone: 'browser',
      schemaVersion: 16,
    },
  },
}
```

The dashboard will be created in _*General*_, and _*FOO*_ will be ignored

**Comment by luizberti** [comment]
An update on this, deleting all of them and recreating didn't seem to have worked the first time I did it. I ended up redoing that a second time and it got picked up.

Still, it doesn't seem to track correctly and marks them as `unchanged` when folder settings are changed, so it's still an issue, but at least seems to have a workaround now

**Comment by janwillies** [comment]
Can you check with master from today please? This just went in: https://github.com/grafana/grizzly/pull/42#pullrequestreview-503776894

**Comment by malcolmholmes** [comment]
Actually it didn't. But, I'm working on this at the moment. #42 got me some of the way. Should be merged tomorrow some time.

**Comment by janwillies** [comment]
whoops my bad, should have read more carefully. Thanks for working on this!
