### ISSUE TITLE
[Bug]: Nil pointer dereference when pushing new datasource to grafana server

### ISSUE THREAD

**Issue by cccs-ajstong** [grafana/grizzly#448]
### Grizzly Version

0.4.2

### Expected Behavior

When we do a `grr push` on a datasource that doesn't exist yet on a grafana server, we expect that datasource to be created by grizzly on the grafana server.

### Actual Behavior

A nil pointer dereference error happens in `grizzly/pkg/grafana/datasource-handler.go` line 46 since `existing` is nil because it is a new datasource (`grizzly/pkg/grizzly/workflow.go` line 420).

### Steps to Reproduce

Just using grr push on a datasource that is not on the grafana server.
`grr push datasource.yaml -t Datasource.uid`

**Comment by malcolmholmes** [comment]
This should be fixed by #450.
