### ISSUE TITLE
List and Show Require Visible Resource Definitions

### ISSUE THREAD

**Issue by trotttrotttrott** [grafana/grizzly#45]
Resources must be defined as visible with a single colon for operations to work ([visibilities](https://jsonnet.org/ref/language.html#visibilities)). For example,

```
grafanaDashboards: {
  'my-dash.json': ...
}
```
works while the following is ignored,

```
grafanaDashboards:: {
  'my-dash.json': ...
}
```

As of https://github.com/grafana/grizzly/pull/38, we're rendering mixin Jsonnet to JSON before either operation which strips away the hidden fields.

@sh0rez, @malcolmholmes is this the intended behavior?

**Comment by malcolmholmes** [comment]
This has been fixed.
