### ISSUE TITLE
[Feature Request]: Support SSO

### ISSUE THREAD

**Issue by F21** [grafana/grizzly#451]
### Feature Request

Grafana users signed in via SSO do not have a password, so it's not possible to use `grr config set grafana.user` and `grr config set grafana.token` for SSO users.

The current work around would be for the SSO user to create a service account and service account token and set it using `grr config set grafana.token`.

This is a bit clunkly as the user must remember to delete the service account after using it and they need to be given permissions to create service accounts.

It would be nice if grizzly supports SSO login, for example, if it could open the browser to prompt for the user to log in, which then returns a token to grizzly.

**Comment by F21** [comment]
If grizzly is able to use Grafana's session cookies, per https://github.com/grafana/grizzly/issues/258, then potentially, SSO can be compeleted on Grafana's side and return a token to grizzly.

**Comment by K-Phoen** [comment]
Since supporting alternative authentication methods is likely to require changes within Grafana itself, we'll close this issue for now and reconsider implementing it at a later stage when Grafana allows it.
