### ISSUE TITLE
[Feature Request]: Grr Serve - Ability to filter resources

### ISSUE THREAD

**Issue by F21** [grafana/grizzly#452]
### Feature Request

I am using grizzly as part of a terraform project. IaC is managed through terraform, but I want to use grizzly to edit my dashboards as it provides a UI to do so.

As there are non-grafana resources in my projects directory, when I run `grr serve .` from the root of the project's directory, I get an error in the web ui warning about a bunch of unrecognized files:
```
unrecognized format for .git/HEAD
unrecognized format for .git/config
unrecognized format for .git/description
unrecognized format for .git/hooks/applypatch-msg.sample
unrecognized format for .git/hooks/commit-msg.sample
unrecognized format for .git/hooks/fsmonitor-watchman.sample
unrecognized format for .git/hooks/post-update.sample
...
```

I would like to be able to silence these errors, or provide some sort of filter to pick up dashboards / resources from a particular subdirectory with a particular extension, for example: `dashboards/**/*.json` and ignore everything else.

**Comment by malcolmholmes** [comment]
you get an error in the web UI, or the Grizzly server console? Surely the latter. How do these warnings cause you a problem? I assume most people won't pay much attention to the console when using `grr serve`.

**Comment by F21** [comment]
The errors are in the Web UI.

**Comment by malcolmholmes** [comment]
Can you paste a screenshot? I don't recall them making it to the web UI, so would be useful to see it.

**Comment by F21** [comment]
See here:
![Fast Screenshot 2024-06-14 at 08 36 31](https://github.com/grafana/grizzly/assets/2263040/0b4de1f3-b809-43b5-bd10-c2b027f77481)

**Comment by malcolmholmes** [comment]
Ahhh! So not on a Grafana page, but on the "index" page. That makes sense now, thanks!
