### ISSUE TITLE
[Bug]: 401 Unauthorized Errors when selecting a dashbaord 

### ISSUE THREAD

**Issue by lorrrrrrrenzo** [grafana/grizzly#454]
### Grizzly Version

v0.4.2

### Expected Behavior

When selecting a dashboard on Grizzly Server, I expect to be able navigate to a dashboard's page. 

### Actual Behavior

I receive a 401 Unauthorized error.

### Steps to Reproduce

0. Use Amazon Managed Grafana
1. `grr serve ./items`
2. Open `localhost:8080`
3. Click a dashboard
4. Observe the 401 Unauthorized error in the event log. 

I suspect that the issue here is the same one as https://github.com/grafana/grizzly/issues/26, which suggests that the solution lies in ensuring that the Authorization key is included in the request to the Grafana endpoint when using Grizzly Server's frontend. This PR is also worth a look: https://github.com/grafana/grizzly/pull/197

**Comment by malcolmholmes** [comment]
Have you configured Grizzly to connect to your AMG instance with a service account before running `grr serve`? In my experience, whenever I see "Unauthorized" errors, they are actually because I did something wrong in terms of authenticating myself.

**Comment by K-Phoen** [comment]
Closing this since there hasn't been any update in a while.

Feel free to reopen an issue if the issue persists :)
