### ISSUE TITLE
Listing By UID Can Be Cryptic for Humans

### ISSUE THREAD

**Issue by trotttrotttrott** [grafana/grizzly#46]
> Resource is a general representation of something Grizzly manages...

`Resource` is an interface with a `Kind` and a `UID`. For rules, UID is their group names which tend to convey meaning to humans. For dashboards, it's a mix:

* You can set it to something meaningful.
* If you leave it blank, Grafana generates one. Usually a random string like, `5MQOqeFMk`. And `list` and `show` don't know about them so you'll get the following if you omit UID in more than one dashboard:
  ```
  ▸ grr list vendor/loki-mixin/dashboards.libsonnet
  UID '' claimed by 'loki-writes.json' is also used by 'loki-reads.json'. UIDs must be unique.
  ```
* You can set it to something cryptic. For example, kubernetes-mixin:
  https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/5c07e1de2c8ea4f8fdcc1985712daa5e751a327f/config.libsonnet#L35-L59. `list` and `show` are aware of them, but you have no idea what they are without additional context.

It seems to me we also need an identifier that's more likely to convey meaning - which is probably the dashboard keys (which is what used to be displayed on `list` and `show`). I'm curious if anyone else has an opinion about that and what some ideas are on where to set additional resource metadata.

**Comment by malcolmholmes** [comment]
I suspect this has been improved by the kubernetes style envelopes that Grizzly now uses. Each resource has a metadata/name that uniquely identifies it. This will have some relation to UIDs/specifics within the resource, as the metadata name is not pushed to the endpoint. Closing, unless further exploration is needed.
