### ISSUE TITLE
[Bug]: AlertRuleGroup get command fails with UID-s containing dot .

### ISSUE THREAD

**Issue by onutu** [grafana/grizzly#516]
### Grizzly Version

 v0.6.0

### Expected Behavior

Get the alert rule group spec

### Actual Behavior

Error : FATAL couldn't find a handler for `AlertRuleGroup.<some-uid>`: handler not found

### Steps to Reproduce

- retrieve alert rule groupes using `grr list -r -t AlertRuleGroup`
- UIDs are formatted like this : `<some-uid>.<some-text>`
- try to get one of these alert rule groups : `grr get AlertRuleGroup.<some-uid>.<some-text>`

**Comment by K-Phoen** [comment]
Thanks for reporting this issue :)

I started working on a fix in #517
