### ISSUE TITLE
[Feature Request]: Ability to handle notification policy sub-trees

### ISSUE THREAD

**Issue by onutu** [grafana/grizzly#530]
### Feature Request

The notification policy is handled as a sigle tree object, would it be possible to have some configuration in order to manipulate a sub tree only ? This would be very convenient if different teams are sharing the same grafana alerting system, each one with its own notification policy sub-tree.

**Comment by Duologic** [comment]
This is similar to the request here: https://github.com/grafana/crossplane-provider-grafana/issues/201

I believe this requires support from the API upstream.

**Comment by onutu** [comment]
As a final Grizzly user, I would just like to be able to handle our team sub-tree without concerning about other teams sub-trees. 
Is there any chance to have such a feature in the future (built upon a proper grafana API ou through some grizzly local magic) or should I start coding a workaround on my side ?
