### ISSUE TITLE
Command apply accept many files

### ISSUE THREAD

**Issue by gutorc92** [grafana/grizzly#64]
The command apply should accept many files to be applied at once.

**Comment by janakerman** [comment]
I think this would be quite useful for `watch` too. I'm currently maintaining a single Jsonnet file, importing other dashboards as an entry point. It works well enough but it is one more file to edit with every new dashboard.

**Comment by malcolmholmes** [comment]
I have just merged a `-d` directory feature that is aimed at a directory of yaml files. It expects rhe files to be named in a particular way. I still need to document this. It should also work for jsonnet, although I have not actually tried this yet.

**Comment by malcolmholmes** [comment]
Grizzly now does not require `-d`. If the argument is a directory, it will react accordingly. Closing this issue as effectively done.
