### ISSUE TITLE
grr apply folder with name not supported

### ISSUE THREAD

**Issue by Sanhajio** [grafana/grizzly#70]
`pkg/grafana/dashboards.go|236 func findOrCreateFolder(UID string) (int64, error)` 
only finds folder if the jsonnet file provides UID, 
```
{
  grafanaDashboardFolder: '3d_JKW0Km',
  grafanaDashboards+:: {
+
  },
}
```

while th test data has:
```
{
  grafanaDashboardFolder: 'sample',
  grafanaDashboards+:: {
+
  },
}
```

*Is setting grafanaDashboardFolder by name not supported, or does it need to be implemented ?*

```
> grr --version
grr version v0.0.1-26-g56c3091-dirty
```

**Comment by haarchri** [comment]
in my installation it is working:

`2020/12/17 11:10:04 grr version v0.0.1`

with following syntax:

```
    grafanaDashboardFolder: 'test',
    grafanaDashboards+:: {
        "test.json"+: {
                "uid": "test-001"
        },
```

**Comment by malcolmholmes** [comment]
dashboard folders are a pain. Try a later version (in master - we need to do another release).

**Comment by malcolmholmes** [comment]
@Sanhajio can we close this?

**Comment by Sanhajio** [comment]
@malcolmholmes yes sure please feel free to close it.
