### ISSUE TITLE
Repository license

### ISSUE THREAD

**Issue by mavimo** [grafana/grizzly#73]
Hi all, does anyone know what's the license model behind grizzly?

At the moment without any specific license is hard to understand if I can contribute and we can't see doc on pkg.go.dev (eg: https://pkg.go.dev/github.com/grafana/grizzly/cmd/grr?utm_source=gopls#Version ).

If someone can provide me a detail on license model I'll send a PR to fix it :)

**Comment by mavimo** [comment]
cc/ @malcolmholmes @trotttrotttrott (since seems you're involved on project bootstrap)

**Comment by malcolmholmes** [comment]
Very good question. You can consider this to be licensed Apache License V2. I will add a license file shortly. Thanks for the observation.

**Comment by mavimo** [comment]
@malcolmholmes ok, thx! Let me know if you need some kind of support on that :)

**Comment by malcolmholmes** [comment]
Resolved in #75. Thanks for pointing out this obvious omission @mavimo .
