### ISSUE TITLE
grr get not working in version 0.10.0

### ISSUE THREAD

**Issue by nahsi** [grafana/grizzly#95]
grr get <provider>.<uid> doesn't work anymore

```
grr get dashboard.TZBbz9TMk
No handler registered to dashboards
```

**Comment by malcolmholmes** [comment]
This probably needs better documenting. Naming was confusing. So it switched to a Kubernetes style naming, apiversion/kind. Therefore the "kind" is now capitalised.

Using `Dashboard` should work for you.

**Comment by nahsi** [comment]
You are right, it works! Thank you.
